name: Update PR count in Port

on:
  workflow_dispatch:

jobs:

  update_pr_count:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Get PR count
      id: prs
      uses: octokit/request-action@v2.0.0
      with:
        route: GET /repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/pulls
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Save PRs to file
      run: echo '${{ steps.prs.outputs.data }}' > prs.json

    - name: Count PRs using Python
      run: |
        PR_COUNT=$(python -c "import json; print(len(json.load(open('prs.json'))))")
          echo "Total pull requests: $PR_COUNT"
          echo "PR_COUNT=$PR_COUNT" >> $GITHUB_ENV

    
    - name: port-github-action
      uses: port-labs/port-github-action@v1.5.0      
      with: 
        clientId: ${{ secrets.PORT_CLIENT_ID }}
        clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
        operation: UPSERT
        identifier: port-github-action
        title: Port Github Action
        blueprint: service
        properties: |
          {
            "open_prs": "${{ env.PR_COUNT }}"
          }
