name: Update PR count in Port

on:
  workflow_dispatch:

jobs:

  update_pr_count:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Get PR count
      id: prs
      uses: octokit/request-action@v2.0.0
      with:
        route: GET /repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/pulls
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: port-github-action
      uses: port-labs/port-github-action@v1.5.0      
      with: 
        clientId: ${{ secrets.PORT_CLIENT_ID }}
        clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
        operation: UPSERT
        identifier: port-github-action
        title: Port Github Action
        blueprint: PortIntegration
        properties: |
          {
            "open_prs": "${{ steps.prs.outputs.data.length }}" 
          }
